# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
from psycopg2.extras import RealDictCursor

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """The LibraryService defines the gRPC endpoints for library operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBook = channel.unary_unary(
                '/library.LibraryService/CreateBook',
                request_serializer=library__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=library__pb2.CreateBookResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.LibraryService/UpdateBook',
                request_serializer=library__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=library__pb2.UpdateBookResponse.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/library.LibraryService/CreateMember',
                request_serializer=library__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.CreateMemberResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library.LibraryService/UpdateMember',
                request_serializer=library__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.UpdateMemberResponse.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.LibraryService/BorrowBook',
                request_serializer=library__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=library__pb2.BorrowBookResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.LibraryService/ReturnBook',
                request_serializer=library__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=library__pb2.ReturnBookResponse.FromString,
                _registered_method=True)
        self.ListBorrowedByMember = channel.unary_unary(
                '/library.LibraryService/ListBorrowedByMember',
                request_serializer=library__pb2.ListBorrowedByMemberRequest.SerializeToString,
                response_deserializer=library__pb2.ListBorrowedByMemberResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/library.LibraryService/ListBooks',
                request_serializer=library__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=library__pb2.ListBooksResponse.FromString,
                _registered_method=True)
def ListMembers(self, request, context):
    """Return all members (no pagination)."""
    conn = self._get_conn()
    try:
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute('SELECT * FROM members ORDER BY id')
            rows = cur.fetchall()
            members = [self._row_to_member(r) for r in rows]
            return library__pb2.ListMembersResponse(members=members)
    finally:
        self._put_conn(conn)

class LibraryServiceServicer(object):
    """The LibraryService defines the gRPC endpoints for library operations.
    """

    def CreateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowedByMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=library__pb2.CreateBookRequest.FromString,
                    response_serializer=library__pb2.CreateBookResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=library__pb2.UpdateBookRequest.FromString,
                    response_serializer=library__pb2.UpdateBookResponse.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=library__pb2.CreateMemberRequest.FromString,
                    response_serializer=library__pb2.CreateMemberResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=library__pb2.UpdateMemberRequest.FromString,
                    response_serializer=library__pb2.UpdateMemberResponse.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=library__pb2.BorrowBookRequest.FromString,
                    response_serializer=library__pb2.BorrowBookResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=library__pb2.ReturnBookRequest.FromString,
                    response_serializer=library__pb2.ReturnBookResponse.SerializeToString,
            ),
            'ListBorrowedByMember': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowedByMember,
                    request_deserializer=library__pb2.ListBorrowedByMemberRequest.FromString,
                    response_serializer=library__pb2.ListBorrowedByMemberResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=library__pb2.ListBooksRequest.FromString,
                    response_serializer=library__pb2.ListBooksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """The LibraryService defines the gRPC endpoints for library operations.
    """

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateBook',
            library__pb2.CreateBookRequest.SerializeToString,
            library__pb2.CreateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateBook',
            library__pb2.UpdateBookRequest.SerializeToString,
            library__pb2.UpdateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateMember',
            library__pb2.CreateMemberRequest.SerializeToString,
            library__pb2.CreateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateMember',
            library__pb2.UpdateMemberRequest.SerializeToString,
            library__pb2.UpdateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/BorrowBook',
            library__pb2.BorrowBookRequest.SerializeToString,
            library__pb2.BorrowBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ReturnBook',
            library__pb2.ReturnBookRequest.SerializeToString,
            library__pb2.ReturnBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowedByMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBorrowedByMember',
            library__pb2.ListBorrowedByMemberRequest.SerializeToString,
            library__pb2.ListBorrowedByMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBooks',
            library__pb2.ListBooksRequest.SerializeToString,
            library__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
